alias http-server='python3 -m http.server'
alias smb-server='impacket-smbserver'
alias ftp-server='twistd -n ftp -r .'
alias git-save='git add -A && git commit -m "Quick Save - $(date --iso-8601=seconds)" && git push'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ls='ls --color=auto'
alias ll='ls -la'

# ---

W_DANGEROUS_FILES_4K="/opt/dangerous_files/fuzz.txt"
W_COMMON_WEB_FILES_4K="/opt/SecLists/Discovery/Web-Content/common.txt"
W_BURP_PARAMETERS_2K="/opt/SecLists/Discovery/Web-Content/burp-parameter-names.txt"
W_DIRB_BIG_20K="/usr/share/wordlists/dirb/big.txt"
W_QUICK_HITS_2K="/opt/SecLists/Discovery/Web-Content/quickhits.txt"
W_FULL_ASCII_94="/opt/SecLists/Fuzzing/alphanum-case-extra.txt"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lh='ls -lh'


# Apt
alias update='sudo apt -y update'
alias upgrade='sudo apt-get -y update && sudo apt-get -y --allow-unauthenticated upgrade && sudo apt-get autoclean && sudo apt-get autoremove && exit 0'
alias search='sudo apt search'
alias links='links2'
# Install and Remove Packages
alias install='sudo apt-get -y install'
alias uninstall='sudo apt-get --purge autoremove '
alias search-installed='sudo dpkg --get-selections '

alias lsdir='ls -ld */'
alias paux='ps aux | grep'
alias cd.='cd ..'
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
alias cd..='cd ..'


# Useful Alias
alias CD='cd'