FROM kalilinux/kali-rolling

ENV _JAVA_OPTIONS -Dawt.useSystemAAFontSettings=on
ENV JAVA_FONTS /usr/share/fonts/truetype

RUN apt update && apt upgrade -y \
    && apt install -y \
    binutils \
    binwalk \
    burpsuite \
    cewl \
    curl \
    dirb \
    dnsutils \
    ffuf \
    gdb \
    ghidra \
    git \
    gobuster \
    hurl \
    imhex \
    jadx \
    jd-gui \
    jq \
    jython \
    libimage-exiftool-perl \
    ltrace \
    make \
    masscan \
    metasploit-framework \
    net-tools \
    nikto nmap \
    nodejs \
    npm \
    patator \
    proxychains \
    pwncat \
    python3-impacket \
    python3-pip \
    python3-venv \
    recon-ng \
    responder \
    rizin-cutter \
    rz-ghidra \
    seclists \
    smbmap \
    socat \
    sqlmap \
    strace \
    tcpdump \
    tmux \
    veil \
    vim \
    weevely \
    wfuzz \
    whatweb \
    wordlists \
    wpscan \
    zaproxy \
    zsh \
    \
    gcc-multilib \
    \
    && apt-get -y clean && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/* \
    \
    && npm install -g ngrok \
    && pip3 install -U uv --break-system-packages \
    && pip3 install setuptools --break-system-packages \
    && pip3 install pwntools --break-system-packages \
    \
    && ln -s /usr/share/impacket/script /usr/bin/impacket-smbserver \
    && ln -s /usr/share/impacket/script /usr/bin/impacket-wmipersist \
    && ln -s /usr/share/impacket/script /usr/bin/impacket-smbexec \
    && ln -s /usr/share/impacket/script /usr/bin/impacket-GetADUsers \
    \
    && sh -c "$(curl -fsSL https://gef.blah.cat/sh)" \
    && sh -c 'echo n | ZSH=/etc/zsh/oh-my-zsh sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"' \ 
    && usermod -s /usr/bin/zsh root \
    && touch ~/.hushlogin

COPY aliases /etc/zsh/aliases
COPY zshrc /etc/zsh/zshrc
COPY tmux.conf /etc/tmux.conf

ENTRYPOINT [ "/usr/bin/zsh" ]